version: "3.4"

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydb
    expose:
      - "5432"
    ports:
      - 5432:5432
    
  dev:
    image: nest4noobs
    build: .
    command: yarn start:dev
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - .:/nest4noobs
      - node_modules:/node_modules
volumes:
   node_modules: {}
